services:
  mysql:
    image: mysql:8.0
    container_name: carpincha-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: carpincha
      MYSQL_USER: carpincha_user
      MYSQL_PASSWORD: carpi123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - carpincha-network

networks:
  carpincha-network:
    driver: bridge

volumes:
  mysql_data:
